services:
  postgres:
    image: postgres:15-alpine
    container_name: sportslive-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: sportslive_admin
      POSTGRES_PASSWORD: SportLive2024SecureDbPassword
      POSTGRES_DB: sports_live_dev
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./backups:/backups
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sportslive_admin -d sports_live_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: sportslive-redis
    restart: unless-stopped
    ports:
      - "127.0.0.1:6379:6379"
    command: >
      redis-server 
      --maxmemory 256mb 
      --maxmemory-policy allkeys-lru
      --requirepass Redis2024CacheSecurePassword
    volumes:
      - ./data/redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5